domain: surulere.dev
url: https://surulere.dev
baseurl: /dotdev1
future: true
frame_class: "frame mw6 pa2 h-100"
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      basepath: "/dotdev1"
relative_permalinks: false
